[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "vite dev"
  targetPort = 5173
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy"
  status = 200
  force = true